### ISSUE TITLE
Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)

### ISSUE THREAD

**Issue by abauville** [lewagon/sinatra-101#9]
I ran into this error when running:
bundle exec ruby app.rb
(That's the first step of the chapter Sinatra App)

The error is: /Users/***/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
        from /Users/***/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1493:in `run!'
        from /Users/***/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-contrib-2.1.0/lib/sinatra/reloader.rb:260:in `run!'
        from /Users/***/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/sinatra-2.1.0/lib/sinatra/main.rb:45:in `block in <module:Sinatra>'

I tried to fix it by installing thin (gem install thin), which didn't work. In the end, I got it to work by adding `gem "thin"` in the Gemfile

**Comment by dmilon** [comment]
Hi @abauville :wave: Thank you for your feedback :pray: 

In fact, the bug was coming from our instructions: we were asking users to launch their app by running `bundle exec ruby app.rb` whereas they should simply run `ruby app.rb` as described in the [Sinatra documentation](http://sinatrarb.com/intro.html) and in other Sinatra challenges of ours like [here](https://github.com/lewagon/fullstack-challenges/blob/80b373c24ea109b6134cb36dd41e9952d9ce59b6/03-AR-Database/01-DB-Design-and-SQL/Optional-01-Jukebox-Sinatra/README.md#L18) and [here](https://github.com/lewagon/fullstack-challenges/blob/80b373c24ea109b6134cb36dd41e9952d9ce59b6/03-AR-Database/04-ActiveRecord-Advanced/03-Sinatra/README.md#L39).

I've just fixed our sinatra setup instructions https://github.com/lewagon/sinatra-101/commit/744693933976ee8ed465d842ae3c5d829969ccca
